import "../../globals.css";
import Navbar from "@/app/[locale]/components/Navbar";
import Footer from "@/app/[locale]/components/Footer";
import {Metadata} from "next";

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // Params is a Promise in Next.js 15
}

export function generateStaticParams() {
  return [{locale: "en"}, {locale: "et"}];
}

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                           params,
                                         }: RootLayoutProps) {
  const {locale} = await params;

  return (
    <html lang={locale}>
    <body className="antialiased with-color">
    <Navbar locale={locale}/>
    <main className="min-h-screen pt-16">{children}</main>
    <Footer/>
    </body>
    </html>
  );
}